# Generated by Django 5.1.3 on 2024-11-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingcost',
            old_name='unit',
            new_name='unitField',
        ),
        migrations.RemoveField(
            model_name='shippingcost',
            name='PriceField',
        ),
    ]
